image: drone-imager
git:
  path: github.com/guruvan/testing
env:
  - GIT_TAG=$(git rev-parse --short HEAD)
  - WORKDIR=$(pwd)
  - IMAGE=$$imageName
  - APP=testing
  - STAGE=PROD
  - REGMAIL=$$registryEmail
  - REGPASS=$$registryPass
  - REGUSER=$$registryUser
  - REGISTRY=$$REGISTRY
script:
  - echo "${STAGE}" > app/.stage
  - echo "${GIT_TAG}" > app/.buildRev
  - echo "run the correct main scripts that would go to /app"
  - echo "then run tests script to verify data is avail & correct"
publish:
  docker:
    docker_host: $$dockerHost
    docker_version: 1.4.1
    registry_login_url: $$registryUrl
    registry_login: false
    username: $$registryUser
    password: $$registryPass
    email: $$registryEmail
    image_name: $$imageName
    tags: [$GIT_TAG,latest]
    keep_builds: false
deploy:
  bash:
    script:
      - cd ${WORKDIR}/.drone
      - ./fleet-deploy.sh
notify:
  irc:
    server: chat.freenode.net
    nick: mazaclub-buildbot
    channel: '#mazaclub-dev'
    on_started: true
    on_success: true
    on_failure: true
